version: "3.9"

services:
  db:
    image: postgres:17
    container_name: finance_tracker_db
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: finance_tracker_pgdata

