spring.application.name=Finance_tracker

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/finance_app
spring.datasource.username=finance_user
spring.datasource.password=finance_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Logging
logging.level.root=DEBUG
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.flyway=DEBUG


# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false

security.jwt.secret-key=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9yTGVhcm5pbmdKV1QxMjM0NTY3ODkw
security.jwt.expiration-time=86400000

